### ISSUE TITLE
In leanpkg.toml, allow git revision commit hash to be replaced by tag name

### ISSUE THREAD

**Issue by juliangilbey** [leanprover-community/mathlib-tools#13]
It would be great if update-mathlib could parse something like the following in leanpkg.toml:

```
[dependencies]
mathlib = {git = "https://github.com/leanprover-community/mathlib", tag = "nightly-2020-02-19"}
```

This would have a couple of significant benefits: it would save having to look up the revision commit hash on github every time an update is wanted, and it would make the dependency much more human-readable.

The code changes required are relatively straightforward; I could write this if wanted.

**Comment by robertylewis** [comment]
I *think* the current behavior is that `leanpkg upgrade` uses the `lean_version` entry in `leanpkg.toml` to choose a commit. If `lean_version = "3.5.1"`, it will check out the `lean-3.5.1` branch of mathlib and insert that commit hash into the toml. In effect this is "update to the latest nightly."

I agree it would be nice to have more manual control over which tag/branch it checks out, e.g. if you want a nightly older than the latest.

But this issue should probably move to https://github.com/leanprover-community/lean since it's more of a `leanpkg` thing than an `update-mathlib` thing.

**Comment by juliangilbey** [comment]
Thanks.  But then I'm very confused indeed :-(

If `leanpkg upgrade` upgrades mathlib to the latest appropriate nightly version of mathlib (and updates the `leanpkg.toml` in the process), then what is the point of `update-mathlib`?

**Comment by bryangingechen** [comment]
`leanpkg upgrade` updates the `.lean` source files for mathlib (and all other dependencies of your project), `update-mathlib` downloads the compiled `.olean` files for mathlib. You could build those `.olean` files yourself (at the cost of some time and power) by running `leanpkg build` instead.

**Comment by juliangilbey** [comment]
Ah, thanks!  So a lovely addition to `update-mathlib` would be a `-h` option which says this and then exits!

**Comment by PatrickMassot** [comment]
Thanks for you contribution. We are closing all pull requests and issues since this tool no longer has any relevance in the Lean 4 era. This repository will now be archived.
