### ISSUE TITLE
SSH problems

### ISSUE THREAD

**Issue by mattearnshaw** [leanprover-community/mathlib-tools#72]
the block of code at https://github.com/leanprover-community/mathlib-tools/blob/77c707eaead3732d0a1527478602649c7e82874e/mathlibtools/leanproject.py#L180 seems to exist to test whether an SSH URL (`git@...`) should be used to clone a project when the latter is given by name. But this test breaks the tool because my `ssh_config` is set to use a specific identity file for the `github.com` host, which `paramiko` does not seem to find automatically

I think perhaps `https` URLs should just be used as a default if a protocol is not specified, otherwise here is an alternative that does an `ssh_config` lookup but the user is potentially prompted twice for their key (once by `paramiko`, then again by `git`): https://github.com/mattearnshaw/mathlib-tools/commit/a6193c7a7144ef8765d9e2b56d633ddf29e1f4bc

**Comment by gebner** [comment]
> I think perhaps `https` URLs should just be used as a default if a protocol is not specified

This is unfortunately not an option because you can't push via `https` if you have 2FA enabled.  (And I am required to enable it because of another project.)

I think parsing the `ssh_config` is the right way to go here.  We also use the public key for `git clone` etc., do we need to change anything there as well to support host-specific keys?

**Comment by mattearnshaw** [comment]
a change is only needed where `paramiko` is used so I think my branch covers it – `git` (or the python module for git) handles the host-specific keys properly by default. By using the `fabric` library, we also don't need to add our own `ssh_config` parsing: https://github.com/leanprover-community/mathlib-tools/compare/master...mattearnshaw:ssh_keyfile

Another option would be to include a flag for `ssh` such that e.g. `leanproject get -S tutorials` would use SSH (of course one can always specify a full URL, or indeed `git remote set-url` to change it post-hoc). It does seem wrong to try to make a connection essentially just to parse a string (to determine by `tutorials` whether we "intended" `git@github.com:leanprover-community/tutorials` or not – most users will not have an intention either way). 

For reference:
you should be able to test this issue by moving your private key to `~/.ssh/github_private_keyfile` and then adding the following to `~/.ssh/config`
```
Host github.com
        IdentityFile ~/.ssh/github_private_keyfile
```

**Comment by PatrickMassot** [comment]
This part of `leanproject` is extremely hackish and brittle. I have neither knowledge or time to work on doing it properly, especially since it works well in default setups. PRs are welcome as long as they don't make it more complicated to use `leanproject` for people who have a default setup. 

Hint: don't assume that anything related to SSH in this project is done for a good reason. I simply tried to get rid of it. Ideally there shouldn't be anything SSH related here, `git` should do all the work. The only reason why we mess up with ssh is to determine git urls. This is very unfortunate because this tends to cause python installation problems on windows.

**Comment by dimpase** [comment]
For people behind firewalls often `ssh` and `https` are the only protocols they can use to communicate with a git server, i.e. `git` protocal communications are not allowed. And `https` has an unfortunate "feature" that it  keeps asking for a password, whereas `ssh` allows a more user-friendly workflow.

**Comment by mattearnshaw** [comment]
@dimpase don't worry, there's no suggestion here to remove SSH support. In my pull request, the defaults are unchanged
